spring:
  datasource:
    url: jdbc:mysql://emp-dev.cacf4tlq4dtc.us-east-1.rds.amazonaws.com:3306/empdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update